'use client';
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ar");

  const translations = {
    en: {
      map: "Search by map",
      list: "Search by list",
      signIn: "Sign In",
      signOut: "Sign Out",
      addProperty: "Add Property",
      language: "العربية",
      menu: "Menu",
      mobile: "Mobile",
      password: "Password",
      invalidCredentials: "Invalid mobile or password",
      welcome: "Welcome",
      forgotPassword: "Forgot Password?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign Up",
      firstName: "First Name",
      lastName: "Last Name",
      confirmPassword: "Confirm Password",
      passwordsDontMatch: "Passwords don't match",
      invalidMobile: "Invalid Syrian mobile number format",
      signupError: "Signup failed",
      networkError: "Network error",
      loading: "Processing...",
      alreadyHaveAccount: "Already have an account?",
      signinAfterSignupFailed: 'Signup successful! Please sign in',
      dashboard: "Dashboard",
      welcomeBack: "Welcome Back",
      mapView: "Map View",
      satelliteView: "Satellite View",
      governorates: "Syrian Governorates",
      loadingMap: "Loading map...",
       profileSettings: 'Profile Settings',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    profileImage: 'Profile Image URL',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully!',
    updateError: 'Update failed. Please try again.',
    networkError: 'Network error. Please check your connection.',
    profileSettings: 'Profile Settings',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    changeImage: 'Change Image',
    imageFormats: 'JPG, PNG up to 5MB',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully!',
    updateError: 'Update failed. Please try again.',
    networkError: 'Network error. Please check your connection.',
    uploadError: 'Image upload failed. Please try again.',
    updating: 'Updating...',
    yourProfile: 'Your Profile',
    profileDesc: 'View and edit your personal information',
    manageProfile: 'Manage Profile',
    yourListings: 'Your Listings',
    listingsDesc: 'Manage your property listings',
    viewListings: 'View Listings',
    subscription: 'Subscription',
    subscriptionDesc: 'Manage your subscription plan',
    viewPlan: 'View Plan',
    dashboardDesc: 'Manage your account and listings from here',
     subscription: 'Subscription',
  freePlan: 'Free Plan',
  goldenPlan: 'Golden Plan',
  diamondPlan: 'Diamond Plan',
  freePlanDesc: 'Basic features',
  goldenPlanDesc: 'Enhanced visibility',
  diamondPlanDesc: 'Premium experience',
  currentPlan: 'Your Current Plan',
  upgrade: 'Upgrade Now',
  selectPlan: 'Select Plan',
  features: 'Features',
  subscriptionDesc: 'Choose the plan that works best for you. Upgrade or downgrade at any time.',
  liked: 'Liked',
  noLikedProperties: 'You have not liked any properties yet',
browseProperties: 'Browse Properties',
viewDetails: 'View Details',
  chat: 'Chats',
  noConversations: 'You have no messages yet',
  notifications: 'Notifications',
markAllRead: 'Mark all as read',
noNotifications: 'No notifications yet',
viewAll: 'View all notifications',
  noNotificationsDesc: 'Your notifications will appear here when you have new activity.',




    

    },
    ar: {
      map: "البحث بالخريطة",
      list: "البحث بالقائمة",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      addProperty: "إضافة عقار",
      language: "English",
      menu: "القائمة",
      mobile: "رقم الجوال",
      password: "كلمة المرور",
      invalidCredentials: "رقم الجوال أو كلمة المرور غير صحيحة",
      welcome: "مرحباً",
      forgotPassword: "نسيت كلمة المرور؟",
      dontHaveAccount: "ليس لديك حساب؟",
      signUp: "تسجيل",
      firstName: "الاسم الأول",
      lastName: "الاسم الأخير",
      confirmPassword: "تأكيد كلمة المرور",
      passwordsDontMatch: "كلمات المرور غير متطابقة",
      invalidMobile: "صيغة رقم الجوال السوري غير صالحة",
      signupError: "فشل إنشاء الحساب",
      networkError: "خطأ في الشبكة",
      loading: "جاري المعالجة...",
      alreadyHaveAccount: "هل لديك حساب بالفعل؟",
      signinAfterSignupFailed: 'تم التسجيل بنجاح! يرجى تسجيل الدخول',
      dashboard: "لوحة التحكم",
      welcomeBack: "أهلا بك يا ",
      mapView: "عرض الخريطة",
      satelliteView: "عرض الأقمار الصناعية",
      governorates: "المحافظات السورية",
      loadingMap: "جاري تحميل الخريطة...",
      profileSettings: 'إعدادات الملف الشخصي',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    mobileNumber: 'رقم الهاتف',
    profileImage: 'رابط صورة الملف الشخصي',
    updateProfile: 'تحديث الملف الشخصي',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    updateError: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
    networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
    profileSettings: 'إعدادات الملف الشخصي',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    mobileNumber: 'رقم الهاتف',
    changeImage: 'تغيير الصورة',
    imageFormats: 'JPG, PNG بحد أقصى 5MB',
    updateProfile: 'تحديث الملف الشخصي',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    updateError: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
    networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
    uploadError: 'فشل تحميل الصورة. يرجى المحاولة مرة أخرى.',
    updating: 'جارٍ التحديث...',
    yourProfile: 'ملفك الشخصي',
    profileDesc: 'عرض وتعديل معلوماتك الشخصية',
    manageProfile: 'إدارة الملف',
    yourListings: 'عقاراتك',
    listingsDesc: 'إدارة قوائم العقارات الخاصة بك',
    viewListings: 'عرض العقارات',
    subscription: 'الاشتراك',
    subscriptionDesc: 'إدارة خطة الاشتراك الخاصة بك',
    viewPlan: 'عرض الخطة',
    dashboardDesc: 'ادخل حسابك وعقاراتك من هنا',
    subscription: 'الاشتراك',
  freePlan: 'الباقة المجانية',
  goldenPlan: 'الباقة الذهبية',
  diamondPlan: 'الباقة الماسية',
  freePlanDesc: 'ميزات أساسية',
  goldenPlanDesc: 'ظهور مميز',
  diamondPlanDesc: 'تجربة مميزة',
  currentPlan: 'باقتك الحالية',
  upgrade: 'ترقية الآن',
  selectPlan: 'اختر الباقة',
  features: 'المميزات',
  subscriptionDesc: 'اختر الباقة التي تناسبك. يمكنك الترقية أو التخفيض في أي وقت.',
  liked: 'المفضلة',
  noLikedProperties: 'لم تقم بإضافة أي عقارات إلى المفضلة بعد',
browseProperties: 'تصفح العقارات',
viewDetails: 'عرض التفاصيل',
chat: ' المحادثات',
noConversations: 'لا توجد لديك أي محادثات بعد',
notifications: 'الإشعارات',
markAllRead: 'تحديد الكل كمقروء',
noNotifications: 'لا توجد إشعارات بعد',
viewAll: 'عرض جميع الإشعارات',
  noNotificationsDesc: 'ستظهر إشعاراتك هنا عندما يكون لديك نشاط جديد.',


    }
  };

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === "en" ? "ar" : "en");
  };

  return (
    <LanguageContext.Provider value={{ language, translations, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};